__init__.py
from flask import Flask, redirect, url_for
from routes.vendas import vendas_route
from routes.estoque import estoque_route
from routes.dashboard import dashboard_route
from routes.cadastro import cadastro_route
from routes.login import login_route

app = Flask(__name__)
app.config['SECRET_KEY']='dev'

app.register_blueprint(vendas_route, url_prefix="/vendas")
app.register_blueprint(estoque_route, url_prefix="/estoque")
app.register_blueprint(dashboard_route, url_prefix="/dashboard")
app.register_blueprint(cadastro_route, url_prefix="/cadastro")
app.register_blueprint(login_route, url_prefix="/login")

@app.route('/')
def home():
    return redirect(url_for('login.home'))  # Redirecione para a rota de login

if __name__ == '__main__':
    app.run(debug=True) 

routes/cadastro.py
from flask import Blueprint, render_template, request, url_for, redirect
from database.usuarios import USUARIOS

cadastro_route = Blueprint('cadastro', __name__)

@cadastro_route.route('/')
def home():
    return render_template('cadastro.html')

@cadastro_route.route('/', methods=['POST'])
def cadastroUsuario():
    email = request.form.get('email')
    nome = request.form.get('nome')
    senha = request.form.get('senha')
    novo_usuario={
        "id":len(USUARIOS)+1,
        "nome":nome,
        "email":email,
        "senha":senha
    }
    USUARIOS.append(novo_usuario)
    return redirect(url_for('vendas.home'))

routes/dashboard.py
from flask import Blueprint, render_template, request, redirect, url_for
from database.vendas import VENDAS
from database.estoque import ESTOQUE
from database.compras import COMPRAS

dashboard_route = Blueprint('dashboard', __name__)

@dashboard_route.route('/')
def home():
    qtd_vendas = len(VENDAS)
    qtd_estoque = len(ESTOQUE)
    valor_obtido = sum(venda['valor_total'] for venda in VENDAS)
    valor_gasto = sum(int(produto['valor_compra']) * int(produto['quantidade']) for produto in COMPRAS)
    qtd_produtos = sum(int(produto['quantidade']) for produto in COMPRAS)
    qtd_produtos_vendidos = sum(int(venda['quantidade']) for venda in VENDAS)
    lucro =  valor_obtido - valor_gasto


    return render_template('dashboard.html', qtd_vendas=qtd_vendas, qtd_estoque=qtd_estoque, valor_obtido=valor_obtido, valor_gasto=valor_gasto, qtd_produtos=qtd_produtos, qtd_produtos_vendidos=qtd_produtos_vendidos, lucro=lucro)

routes/estoque.py
from flask import Blueprint, render_template, request, redirect, url_for
from database.estoque import ESTOQUE
from database.compras import COMPRAS

estoque_route = Blueprint('estoque', __name__)

@estoque_route.route('/')
def home():
    qtd_produtos = len(ESTOQUE)
    return render_template('estoque.html', qtd_produtos = qtd_produtos, estoque=ESTOQUE)

@estoque_route.route('/<int:produto_id>/delete', methods=['DELETE'])
def deleteProduto(produto_id):
    global ESTOQUE
    ESTOQUE = [u for u in ESTOQUE if u['id'] != produto_id]
    qtd_produtos = len(ESTOQUE)
    return render_template('estoque.html', qtd_produtos = qtd_produtos, estoque=ESTOQUE)

@estoque_route.route('/', methods=['POST'])
def inserirProduto():
    dados=request.json
    if any(produto['nome'] == dados['nome'] for produto in ESTOQUE):
        return {'message': 'Produto já existe.'}, 400
    novo_produto={
        "id":len(ESTOQUE)+1,
        "nome":dados['nome'],
        "quantidade":dados['quantidade'],
        "valor_venda":dados['preco_compra'],
        "valor_compra":dados['preco_venda'],
        "valor_total": int(dados['preco_compra']) *  int(dados['quantidade'])
    }
    ESTOQUE.append(novo_produto)
    COMPRAS.append(novo_produto)
    return render_template('itemEstoque.html', produto=novo_produto)

@estoque_route.route('/<int:produto_id>/edit', methods=['GET'])
def editProduto(produto_id):
    produto = next((u for u in ESTOQUE if u['id'] == produto_id), None)
    if produto is None:
        return "Produto não encontrado", 404
    return render_template('formEstoque.html', produto=produto)


@estoque_route.route('/<int:produto_id>/update', methods=['PUT'])
def updateProduto(produto_id):
    produto_editado = None
    data = request.json
    for u in ESTOQUE:
        if u['id'] == produto_id:
            u['nome'] = data['nome']
            u['quantidade'] = data['quantidade']
            u['valor_venda'] = data['valor_venda']
            u['valor_compra'] = data['valor_compra']
            u['valor_total'] = data['valor_total']
            produto_editado = u
    return render_template('itemProduto.html', produto=produto_editado)


@estoque_route.route('/new', methods=['GET'])
def formEstoque():
    return render_template('formEstoque.html')

routes/login.py
from flask import Blueprint, render_template, request, url_for, redirect
from database.usuarios import USUARIOS

login_route = Blueprint('login', __name__)

@login_route.route('/')
def home():
    return render_template('login.html')

@login_route.route('/', methods=['POST'])
def check_login():
    email_input = request.form.get('email')
    senha_input = request.form.get('senha')

    usuario = next((u for u in USUARIOS if u['email'] == email_input), None)
    
    if usuario:
        if usuario['senha'] == senha_input:
            return redirect(url_for('vendas.home'))
        else:
            return('senha incorreta')
    else:
        return('usuario nao encontrado')

routes/vendas.py
from flask import Blueprint, render_template, request, redirect, url_for
from database.vendas import VENDAS
from database.estoque import ESTOQUE

vendas_route = Blueprint('vendas', __name__)

@vendas_route.route('/')
def home():
    qtd_vendas = len(VENDAS)
    produtos_estoque = [{'nome': prod['nome'], 'id': prod['id']} for prod in ESTOQUE]
    return render_template('vendas.html', qtd_vendas=qtd_vendas, vendas=VENDAS, produtos=produtos_estoque)


@vendas_route.route('/', methods=['POST'])
def inserirVenda():
    dados = request.json
    if any(venda['produto'] == dados['produto'] and venda['data'] == dados['data'] for venda in VENDAS):
        return {'message': 'Venda já existe.'}, 400
    produto = next((prod for prod in ESTOQUE if prod['nome'] == dados['produto']), None)

    if not produto:
        return {'message': 'Produto não encontrado no estoque.'}, 404
    
    if produto['quantidade'] < int(dados['quantidade']):
        return {'message': 'Quantidade insuficiente em estoque.'}, 400
    
    
    novo_venda = {
        "id": len(VENDAS) + 1,
        "produto": dados['produto'],
        "data": dados['data'],
        "quantidade": dados['quantidade'],
        "valor_uni": produto['valor_venda'],
        "valor_total": int(produto['valor_venda']) * int(dados['quantidade'])
    }

    VENDAS.append(novo_venda)
    produto['quantidade'] -= int(dados['quantidade'])
    return render_template('itemVenda.html', venda=novo_venda)
    
@vendas_route.route('/<int:venda_id>/delete', methods=['DELETE'])
def deleteVenda(venda_id):
    global VENDAS
    VENDAS = [u for u in VENDAS if u['id'] != venda_id]
    qtd_vendas = len(VENDAS)
    return render_template('vendas.html', qtd_vendas=qtd_vendas, vendas=VENDAS)

templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/main.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>
    <title>Caixa do Zé</title>
</head>
<body class="body-cadastro">
    <div id="container-form">
        <h1 id="title">Faça seu cadastro</h1>
        <div id="line"></div>
        <form class="c-form" action="{{url_for('cadastro.cadastroUsuario')}}" method="post" c-reload-container="true">
            <div class="mb-3">
              <label class="form-label">Email</label>
              <input type="email" name="email" class="form-control" id="exampleInputEmail">
            </div>
            <div class="mb-3">
              <label class="form-label">Nome</label>
              <input type="text" name="nome" class="form-control" id="exampleInputName">
            </div>
            <div class="mb-3">
                <label class="form-label">Senha</label>
                <input type="password" name="senha" class="form-control" id="exampleInputPassword">
              </div>
            <button type="submit" class="btn btn-cadastro">Cadastrar</button>
            <p>Já tem uma conta? <a href="/login">Login</a></p>
          </form>
    </div>
</body>
</html>

templates/dashboard.html
{% extends 'navegacao.html' %}
{% block conteudo %}
    <div id="dashboard-page">
        <h1 id="title-dashboard">Movimentação Financeira</h1>
        <div id="dashboard-container">
            <div id="top-dashboard">
                <div id="entradas">
                    <span>Entradas</span>
                    <div>
                        <p>Vendas realizadas: {{qtd_vendas}}</p>
                        <p>Valor obtido: R${{valor_obtido}}</p>
                    </div>
                </div>
                <div id="saidas">
                    <span>Saidas</span>
                    <div>
                        <p>Compras realizadas: {{qtd_estoque}}</p>
                        <p>Valor gasto: R${{valor_gasto}}</p>
                    </div>
                </div>
                <div id="estoque">
                    <span>Estoque</span>
                    <div>
                        <p>Quantidade em estoque: {{qtd_produtos}}</p>
                        <p>Quantidade de itens vendidos: {{qtd_produtos_vendidos}}</p>
                    </div>
                </div>
            </div>
            <div id="resumo-container">
                <span>Total</span>
                <p id="lucro">
                    R$ {{lucro}} de lucro obtido
                </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/estoque.html
{% extends 'navegacao.html' %}
{% block conteudo %}
    <div id="modal_produto">
        <div id="modal-container">
            <span onclick="close_addproduto()" id="close-modal" class="material-symbols-outlined">disabled_by_default</span>
            <h2>Cadastrar produto</h2>
            <form c-append="#lista-produtos" class="c-form addprodutoform" action="{{url_for('estoque.inserirProduto')}}" method="POST">
                <div class="mb-3">
                    <label class="form-label">Nome do Produto</label>
                    <input type="text" name="nome" class="form-control" id="exampleInputEmail">
                  </div>
                  <div class="mb-3">
                    <label class="form-label">Quantidade</label>
                    <input type="number" name="quantidade" class="form-control" id="exampleInputName">
                  </div>
                  <div class="mb-3">
                      <label class="form-label">Preço de Compra</label>
                      <input type="number" name="preco_compra" class="form-control" id="exampleInputPassword">
                  </div>
                  <div class="mb-3">
                    <label class="form-label">Preço de Venda</label>
                    <input type="number" name="preco_venda" class="form-control" id="exampleInputPassword">
                </div>
                <button type="submit" class="btn btn-add-produto">Cadastrar</button>
            </form>
        </div>
    </div>
    <div class="modal_produto_edit">
        <div id="modal-container-edit">
            <span onclick="close_editproduto()" id="close-modal-edit" class="material-symbols-outlined">disabled_by_default</span>
            <h2>Editar produto</h2>
            <div id="form-produto" c-container="{{url_for('estoque.formEstoque')}}"></div>
        </div>
    </div>
    <div class="container-estoque">
        <div id="header-estoque">
            <div>
                <h1>Produtos</h1>
                <span>{{ qtd_produtos }} Produtos cadastrados</span>
            </div>
            <button onclick="open_addproduto()" type="button" class="btn btn-estoque"><span class="material-symbols-outlined">add_circle</span>Produto</button>
        </div>
        <div id="main-estoque">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Produto</th>
                    <th scope="col">Estoque</th>
                    <th scope="col">Preço da Compra</th>
                    <th scope="col">Preço da Venda</th>
                    <th scope="col">Ações</th>
                  </tr>
                </thead>
                <tbody id="lista-produtos">
                  {% for produto in estoque %}
                        {% include 'itemEstoque.html' %}
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
{% endblock %}

templates/formEstoque.html
<form {% if produto %} action="{{url_for('estoque.updateProduto', id=produto.id)}}" method="PUT" c-swap="produto--{{produto.id}}" c-reload-container="true" class="c-form" {% endif %}>
    <div class="mb-3">
        <label class="form-label">Nome do Produto</label>
        <input type="text" name="nome" class="form-control" {% if produto %} value="{{produto.nome}}" {% endif %}>
    </div>
    <div class="mb-3">
        <label class="form-label">Quantidade</label>
        <input type="number" name="quantidade" class="form-control" {% if produto %} value="{{produto.quantidade}}" {% endif %}>
    </div>
    <div class="mb-3">
        <label class="form-label">Preço de Compra</label>
        <input type="number" name="preco_compra" class="form-control" {% if produto %} value="{{produto.valor_compra}}" {% endif %}>
    </div>
    <div class="mb-3">
        <label class="form-label">Preço de Venda</label>
        <input type="number" name="preco_venda" class="form-control" {% if produto %} value="{{produto.valor_venda}}" {% endif %}>
    </div>
    <button type="submit" class="btn btn-edit-produto">Editar</button>
</form>

templates/formProduto.html
<div class="modal_produto_edit">
    <div id="modal-container-edit">
        <span onclick="close_editproduto()" id="close-modal-edit" class="material-symbols-outlined">disabled_by_default</span>
        <h2>Editar produto</h2>
        <form class="c-form" {% if usuario %} c-swap="usuario--{{usuario.id}}" action="{{url_for('estoque.updateProduto', produto_id=produto.id)}}" {% endif %} method="PUT">
            <div class="mb-3">
                <label class="form-label">Nome do Produto</label>
                <input type="text" name="nome" class="form-control" {% if usuario %} value="{{produto.nome}}" {% endif %}>
            </div>
            <div class="mb-3">
                <label class="form-label">Quantidade</label>
                <input type="number" name="quantidade" class="form-control" {% if usuario %} value="{{produto.quantidade}}" {% endif %}>
            </div>
            <div class="mb-3">
                <label class="form-label">Preço de Compra</label>
                <input type="number" name="preco_compra" class="form-control" {% if usuario %} value="{{produto.valor_compra}}" {% endif %}>
            </div>
            <div class="mb-3">
                <label class="form-label">Preço de Venda</label>
                <input type="number" name="preco_venda" class="form-control" {% if usuario %} value="{{produto.valor_venda}}" {% endif %}>
            </div>
            <button type="submit" class="btn btn-edit-produto">Editar</button>
        </form>
    </div>
</div>

templates/itemEstoque.html
<tr>
    <th scope="row">{{produto.nome}}</th>
    <td>{{produto.quantidade}}</td>
    <td>R${{produto.valor_compra}}</td>
    <td>R${{produto.valor_venda}}</td>
    <td>
        <div>
            <button c-delete="{{url_for('estoque.deleteProduto', produto_id=produto.id)}}" c-remove-closest="tr"  type="button" class="btn btn-danger" ><span class="material-symbols-outlined delete-icon">delete</span></button>
            <button type="button" onclick="open_editproduto({})" class="btn btn-light" c-target="#form-produto"><span class="material-symbols-outlined edit-icon">edit</span></button>
        </div>
    </td>
</tr>

templates/itemVenda.html
<tr></tr>
    <th scope="row">{{venda.produto}}</th>
    <td>{{venda.data}}</td>
    <td>{{venda.quantidade}}</td>
    <td>R${{venda.valor_uni}}</td>
    <td>R${{venda.valor_total}}</td>
    <td>
        <div>
            <button c-delete="{{url_for('vendas.deleteVenda', venda_id=venda.id)}}" c-remove-closest="tr"  type="button" class="btn btn-danger" ><span class="material-symbols-outlined delete-icon">delete</span></button>
        </div>
    </td>
</tr>

templates/login.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/main.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>
    <title>Caixa do Zé</title>
</head>
<body class="body-cadastro">
    <div id="container-form">
        <h1 id="title">Faça seu login</h1>
        <div id="line"></div>
        <form class="c-form" action="{{url_for('login.check_login')}}" method="post" c-reload-container="true">
            <div class="mb-3">
              <label class="form-label">Email</label>
              <input type="email" name="email" class="form-control" id="exampleInputEmail">
            </div>
            <div class="mb-3">
                <label class="form-label">Senha</label>
                <input type="password" name="senha" class="form-control" id="exampleInputPassword">
              </div>
            <button type="submit" class="btn btn-cadastro">Login</button>
            <p>Não tem uma conta? <a href="/cadastro">Cadastre-se</a></p>
          </form>
    </div>
</body>
</html>

templates/navegacao.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/main.css">
    <script src="../static/cru.js" defer></script>
    <script src="../static/js/estoque.js" defer></script>
    <link rel="stylesheet" href="../static/css/dashboard.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>
    <title>Caixa do Zé</title>
</head>
<body class="w-100 vh-100 d-flex flex-column align-items-center">
    <header class="d-flex p-3  gap-3 w-100 h-auto justify-content-between align-items-center">
        <img id="logo-header" style="width: 50px;" src="../static/assets/logo.png" alt="">
        <nav class="d-flex gap-5 justify-content-between align-items-between">
            <a href="/estoque">Estoque</a>
            <a href="/vendas">Vendas</a>
            <a href="/dashboard">Dashboard</a>
        </nav>
        <a href="/login"><span class="material-symbols-outlined">logout</span></a>
        
    </header>
    <body class="h-auto">
        {% block conteudo %} {% endblock %}
    </body>
</body>
</html>

templates/vendas.html
{% extends 'navegacao.html' %}
{% block conteudo %}
    <div id="modal_venda">
        <div id="modal-container-vendas">
            <span onclick="close_addvenda()" id="close-modal-vendas" class="material-symbols-outlined">disabled_by_default</span>
            <h2>Cadastrar venda</h2>
            <form c-append="#lista-vendas" class="c-form addvendaform" action="{{url_for('vendas.inserirVenda')}}" method="POST">
                <label class="form-label">Produto</label>
                    <select name="produto" class="form-control">
                        {% for produto in produtos %}
                            <option value="{{ produto.nome }}">{{ produto.nome }}</option>
                        {% endfor %}
                    </select>
                <div class="mb-3">
                    <label class="form-label">Data</label>
                    <input type="date" name="data" class="form-control" id="exampleInputName">
                </div>
                <div class="mb-3">
                    <label class="form-label">Quantidade</label>
                    <input type="number" name="quantidade" class="form-control" id="exampleInputName">
                </div>
                <button type="submit" class="btn btn-add-produto">Cadastrar</button>
            </form>
        </div>
    </div>
    <div class="container-vendas">
        <div id="header-vendas">
            <div>
                <h1>Vendas</h1>
                <span>{{ qtd_vendas }} Vendas realizadas</span>
            </div>
            <button onclick="open_addvenda()" type="button" class="btn btn-venda"><span class="material-symbols-outlined">add_circle</span>Venda</button>
        </div>
        <div id="main-vendas">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Produto</th>
                    <th scope="col">Data</th>
                    <th scope="col">Quantidade</th>
                    <th scope="col">Valor Unitário</th>
                    <th scope="col">Valor Total</th>
                    <th scope="col">Ação</th>
                </tr>
                </thead>
                <tbody id="lista-vendas">
                {% for venda in vendas %}
                        {% include 'itemVenda.html' %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}